version: "3.8"

services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./path/to/backend:/app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development

  frontend:
    build:
      context: ./app/certificates-app
      dockerfile: Dockerfile
    volumes:
      - ./app/certificates-app:/app
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
